### ISSUE TITLE
[Bug] Throws an error if the directory was changed after launching.

### ISSUE THREAD

**Issue by stpr-dev** [ozok/OooPlayer#1]
If, for example, you extract the portable version and put it in any folder. If the folder was moved or you changed the the name of the folder etc, then it throws an error. You can still launch the application, but will throw the error even when you try to quit.
I tested this out by first extracting in a folder called "oooplayer 11", launching the software and then renaming the directory to "oooplayer". 
Attaching log.
[bugreport.txt](https://github.com/ozok/OooPlayer/files/111637/bugreport.txt)

P.S. For some reason, it says OS is windows 8 while mine is actually 10.

**Comment by ozok** [comment]
You should not do that. Program loads some files at startup and paths should not be changed.
